const DB_NAME='qlnhv-personal', DB_VERSION=1;
let db, sessionKey, records=[];
const $=id=>document.getElementById(id);
const enc=new TextEncoder(), dec=new TextDecoder();
const modules=[
 {id:'hoso',name:'Hồ sơ một cửa',ready:true,description:'Tiếp nhận, xử lý, hướng dẫn, trả kết quả và theo dõi hồ sơ.',features:['Tiếp nhận hồ sơ','Hồ sơ tạm nhận/chưa ra giấy','Giấy biên nhận','Hướng dẫn hoàn thiện','Nhập kết quả xử lý','Trả hồ sơ','Xin lỗi và hẹn lại','Thủ tục hành chính']},
 {id:'doanhnghiep',name:'Doanh nghiệp & quan hệ',description:'Quản lý doanh nghiệp, nhà đầu tư, bên đi vay và các quan hệ liên quan.',features:['Danh mục doanh nghiệp','Nhà đầu tư','Bên đi vay','Quan hệ doanh nghiệp','Chuyển phường/địa bàn']},
 {id:'vay',name:'Vay, trả nợ nước ngoài',description:'Quản lý khoản vay, lịch sử, kế hoạch rút vốn trả nợ và báo cáo.',features:['Thông tin khoản vay','Vay trung dài hạn','Lịch sử khoản vay','Kế hoạch rút vốn/trả nợ','Báo cáo quý','Phân công chuyên viên','Thống kê vay']},
 {id:'dautu',name:'Đầu tư ra nước ngoài',description:'Quản lý dự án đầu tư, nhà đầu tư và tình trạng hoạt động.',features:['Nhập dự án đầu tư','Chi tiết dự án/nhà đầu tư','Dự án ngừng hoạt động','Tra cứu nhập liệu','Thống kê đầu tư','Lưu trữ và tiêu hủy']},
 {id:'daily',name:'Đại lý ngoại tệ',description:'Quản lý đại lý đổi ngoại tệ và đại lý chi trả ngoại tệ.',features:['Đại lý đổi ngoại tệ','Đại lý chi trả ngoại tệ','Liên kết hồ sơ','Danh sách phối hợp','Kiểm tra đại lý']},
 {id:'taikhoan',name:'Tài khoản ngoại tệ ở nước ngoài',description:'Quản lý giấy phép mở tài khoản và báo cáo định kỳ.',features:['Mở tài khoản ngoại tệ','Doanh nghiệp mở tài khoản','Báo cáo quý','Danh sách giấy phép còn hạn','Thống kê quốc gia']},
 {id:'xnk',name:'Xuất nhập khẩu ngoại tệ tiền mặt',description:'Theo dõi quyết định và chi tiết xuất nhập khẩu ngoại tệ tiền mặt.',features:['Quyết định XNK ngoại tệ','Chi tiết từng ngoại tệ','Danh sách ngân hàng','Báo cáo tháng','Mục lục và tổng hợp USD']},
 {id:'vanthu',name:'Văn thư',description:'Quản lý công văn đến, công văn đi và sổ văn thư.',features:['Nhập công văn đến','Nhập công văn đi','Sổ công văn đến','Lưu công văn nội bộ','Lưu công văn bên ngoài']},
 {id:'kiemtra',name:'Kiểm tra & vi phạm',description:'Theo dõi kiểm tra và xử lý vi phạm hành chính.',features:['Nhập thông tin kiểm tra','Nhập xử lý vi phạm','Tình hình xử lý VPHC','Danh sách hồ sơ vi phạm','Báo cáo kiểm tra']},
 {id:'luutru',name:'Lưu trữ & tiêu hủy',description:'Quản lý vị trí lưu, danh mục hồ sơ và tiêu hủy.',features:['Danh mục hồ sơ lưu','Vị trí lưu hồ sơ','Lưu trữ hồ sơ vay','Lưu trữ hồ sơ đầu tư','Danh sách tiêu hủy theo năm']},
 {id:'baocaokhac',name:'F00285 & báo cáo chuyên đề',description:'Nhập và tổng hợp các báo cáo chuyên ngành.',features:['Nhập báo cáo F00285','Chi tiết F00285','Thanh toán với Campuchia','Báo cáo tình hình đối ngoại','Báo cáo chấp hành']},
 {id:'quantri',name:'Quản trị & danh mục',description:'Danh mục dùng chung và công cụ quản trị chương trình.',features:['Thủ tục hành chính','Tiền tệ, quốc gia, ngân hàng','Địa bàn hành chính','Nhóm và loại hình','Quản trị dữ liệu','Tra cứu, thống kê và in ấn']}
];
const reports=['Báo cáo quý vay','Báo cáo công ty vay','Tình hình đối ngoại','Danh sách chi trả ngoại tệ','Kiểm tra đại lý đổi ngoại tệ','Tình hình mở tài khoản ngoại tệ','Thanh toán với Campuchia','Danh mục hồ sơ lưu trữ đầu tư','Danh mục hồ sơ lưu trữ vay','Danh mục dự án ngừng hoạt động','Danh sách đại lý phối hợp','Danh sách giấy phép tài khoản còn hạn','Giấy tiếp nhận hồ sơ','Phiếu hướng dẫn','Nhãn hồ sơ','Sổ theo dõi hồ sơ','Tình hình xử lý vi phạm hành chính','Tổng hợp dự án đầu tư','Báo cáo thủ tục hành chính tháng','Báo cáo XNK ngoại tệ theo tháng','Mục lục XNK ngoại tệ','Báo cáo F00285'];

function openDb(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{const d=r.result;d.createObjectStore('meta',{keyPath:'key'});const s=d.createObjectStore('records',{keyPath:'id'});s.createIndex('mshs','mshs',{unique:true})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
function tx(store,mode='readonly'){return db.transaction(store,mode).objectStore(store)}
function req(r){return new Promise((resolve,reject)=>{r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
const b64=a=>btoa(String.fromCharCode(...new Uint8Array(a)));
const unb64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
async function derive(password,salt){const base=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:310000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
async function verifier(key){return b64(await crypto.subtle.sign ? enc.encode('') : enc.encode('')) || key}
async function encrypt(data,key){const iv=crypto.getRandomValues(new Uint8Array(12));const body=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,enc.encode(JSON.stringify(data)));return{iv:b64(iv),data:b64(body)}}
async function decrypt(box,key){const body=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(box.iv)},key,unb64(box.data));return JSON.parse(dec.decode(body))}
async function keyCheck(key){return encrypt({check:'QLNHV'},key)}

async function setupOrUnlock(password){let meta=await req(tx('meta').get('security'));if(!meta){const salt=crypto.getRandomValues(new Uint8Array(16));sessionKey=await derive(password,salt);meta={key:'security',salt:b64(salt),check:await keyCheck(sessionKey)};await req(tx('meta','readwrite').put(meta))}else{const key=await derive(password,unb64(meta.salt));const value=await decrypt(meta.check,key);if(value.check!=='QLNHV')throw Error('Sai mật khẩu');sessionKey=key}await showApp()}
async function showApp(){$('welcome').hidden=true;$('app').hidden=false;$('lockBtn').hidden=false;records=await req(tx('records').getAll());render()}
function lock(){sessionKey=null;records=[];$('app').hidden=true;$('welcome').hidden=false;$('lockBtn').hidden=true;$('welcomeTitle').textContent='Mở khóa';$('welcomeText').textContent='Nhập mật khẩu của thiết bị này.';$('password').value=''}
function render(filter=''){const q=filter.trim().toLocaleLowerCase('vi');const list=records.filter(x=>[x.mshs,x.mst,x.company,x.procedure].some(v=>(v||'').toLocaleLowerCase('vi').includes(q)));$('recordRows').innerHTML=list.map(x=>`<tr><td>${esc(x.mshs)}</td><td>${esc(x.ngayNhan||'')}</td><td>${esc(x.mst||'')}</td><td>${esc(x.company||'')}</td><td>${esc(x.procedure||'')}</td><td><button class="edit" data-id="${x.id}">Sửa</button></td></tr>`).join('');$('emptyRecords').hidden=list.length>0;$('recordCount').textContent=records.length.toLocaleString('vi');$('companyCount').textContent=new Set(records.map(x=>x.mst).filter(Boolean)).size.toLocaleString('vi');const latest=records.map(x=>x.updatedAt).sort().at(-1);$('updatedAt').textContent=latest?new Date(latest).toLocaleDateString('vi-VN'):'—'}
function renderModules(filter=''){const q=filter.toLocaleLowerCase('vi');$('moduleGrid').innerHTML=modules.filter(m=>(m.name+' '+m.features.join(' ')).toLocaleLowerCase('vi').includes(q)).map(m=>`<button class="module-card" data-module="${m.id}"><span class="status ${m.ready?'ready':''}">${m.ready?'Đã có bản đầu':'Đang chuyển đổi'}</span><h3>${m.name}</h3><p>${m.description}</p></button>`).join('')}
function renderReports(filter=''){const q=filter.toLocaleLowerCase('vi');$('reportList').innerHTML=reports.filter(x=>x.toLocaleLowerCase('vi').includes(q)).map(x=>`<div class="report-row"><span>${x}</span><small>Đang chuyển đổi</small></div>`).join('')}
function openModule(id){const m=modules.find(x=>x.id===id);$('moduleStatus').textContent=m.ready?'Đã có bản đầu':'Đang chuyển đổi';$('moduleStatus').className='status '+(m.ready?'ready':'');$('moduleTitle').textContent=m.name;$('moduleDescription').textContent=m.description;$('moduleFeatures').innerHTML=m.features.map(x=>`<li>${x}</li>`).join('');$('moduleDialog').showModal()}
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(s){$('toast').textContent=s;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2400)}
function openRecord(id){const x=records.find(r=>r.id===id)||{};$('recordId').value=x.id||'';$('mshs').value=x.mshs||'';$('ngayNhan').value=x.ngayNhan||'';$('mst').value=x.mst||'';$('company').value=x.company||'';$('procedure').value=x.procedure||'';$('note').value=x.note||'';$('recordDialog').showModal()}
async function saveRecord(){const x={id:$('recordId').value||crypto.randomUUID(),mshs:$('mshs').value.trim(),ngayNhan:$('ngayNhan').value,mst:$('mst').value.trim(),company:$('company').value.trim(),procedure:$('procedure').value.trim(),note:$('note').value.trim(),updatedAt:new Date().toISOString()};await req(tx('records','readwrite').put(x));const i=records.findIndex(r=>r.id===x.id);i<0?records.push(x):records[i]=x;render($('search').value);toast('Đã lưu hồ sơ')}
async function exportBackup(){const security=await req(tx('meta').get('security'));const payload=await encrypt({version:1,exportedAt:new Date().toISOString(),records},sessionKey);const blob=new Blob([JSON.stringify({format:'QLNHV-BACKUP',salt:security.salt,payload})],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`QLNHV-${new Date().toISOString().slice(0,10)}.qlnhv`;a.click();URL.revokeObjectURL(a.href);toast('Đã tạo file sao lưu mã hóa')}
async function importBackup(){const file=$('importFile').files[0];if(!file)return toast('Hãy chọn file sao lưu');if(!confirm('Khôi phục sẽ thay thế toàn bộ hồ sơ hiện tại. Tiếp tục?'))return;const box=JSON.parse(await file.text());if(box.format!=='QLNHV-BACKUP')throw Error('File không hợp lệ');const key=await derive($('password').value||prompt('Nhập mật khẩu của file sao lưu'),unb64(box.salt));const data=await decrypt(box.payload,key);const t=db.transaction(['records','meta'],'readwrite');t.objectStore('records').clear();data.records.forEach(x=>t.objectStore('records').put(x));const check=await keyCheck(key);t.objectStore('meta').put({key:'security',salt:box.salt,check});await new Promise((res,rej)=>{t.oncomplete=res;t.onerror=()=>rej(t.error)});sessionKey=key;records=data.records;render();toast('Khôi phục thành công')}

document.addEventListener('DOMContentLoaded',async()=>{db=await openDb();renderModules();renderReports();const exists=await req(tx('meta').get('security'));if(exists){$('welcomeTitle').textContent='Mở khóa';$('welcomeText').textContent='Nhập mật khẩu của thiết bị này.'}$('unlockForm').onsubmit=async e=>{e.preventDefault();try{await setupOrUnlock($('password').value)}catch{toast('Mật khẩu không đúng hoặc dữ liệu lỗi')}};$('lockBtn').onclick=lock;document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.view').forEach(v=>v.hidden=v.id!==b.dataset.view)});$('moduleSearch').oninput=e=>renderModules(e.target.value);$('reportSearch').oninput=e=>renderReports(e.target.value);$('moduleGrid').onclick=e=>{const b=e.target.closest('[data-module]');if(b)openModule(b.dataset.module)};$('newRecord').onclick=()=>openRecord();$('search').oninput=e=>render(e.target.value);$('recordRows').onclick=e=>{const b=e.target.closest('.edit');if(b)openRecord(b.dataset.id)};$('recordForm').onsubmit=e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();saveRecord().then(()=>$('recordDialog').close()).catch(()=>toast('Mã hồ sơ đã tồn tại'))};$('exportBtn').onclick=exportBackup;$('importBtn').onclick=()=>importBackup().catch(()=>toast('Không thể đọc file hoặc sai mật khẩu'));if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js')});
