const DB_NAME='qlnhv-personal', DB_VERSION=1;
let db, sessionKey, records=[];
const $=id=>document.getElementById(id);
const enc=new TextEncoder(), dec=new TextDecoder();

function openDb(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{const d=r.result;d.createObjectStore('meta',{keyPath:'key'});const s=d.createObjectStore('records',{keyPath:'id'});s.createIndex('mshs','mshs',{unique:true})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
function tx(store,mode='readonly'){return db.transaction(store,mode).objectStore(store)}
function req(r){return new Promise((resolve,reject)=>{r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
const b64=a=>btoa(String.fromCharCode(...new Uint8Array(a)));
const unb64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
async function derive(password,salt){const base=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:310000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
async function verifier(key){return b64(await crypto.subtle.sign ? enc.encode('') : enc.encode('')) || key}
async function encrypt(data,key){const iv=crypto.getRandomValues(new Uint8Array(12));const body=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,enc.encode(JSON.stringify(data)));return{iv:b64(iv),data:b64(body)}}
async function decrypt(box,key){const body=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(box.iv)},key,unb64(box.data));return JSON.parse(dec.decode(body))}
async function keyCheck(key){return encrypt({check:'QLNHV'},key)}

async function setupOrUnlock(password){let meta=await req(tx('meta').get('security'));if(!meta){const salt=crypto.getRandomValues(new Uint8Array(16));sessionKey=await derive(password,salt);meta={key:'security',salt:b64(salt),check:await keyCheck(sessionKey)};await req(tx('meta','readwrite').put(meta))}else{const key=await derive(password,unb64(meta.salt));const value=await decrypt(meta.check,key);if(value.check!=='QLNHV')throw Error('Sai mật khẩu');sessionKey=key}await showApp()}
async function showApp(){$('welcome').hidden=true;$('app').hidden=false;$('lockBtn').hidden=false;records=await req(tx('records').getAll());render()}
function lock(){sessionKey=null;records=[];$('app').hidden=true;$('welcome').hidden=false;$('lockBtn').hidden=true;$('welcomeTitle').textContent='Mở khóa';$('welcomeText').textContent='Nhập mật khẩu của thiết bị này.';$('password').value=''}
function render(filter=''){const q=filter.trim().toLocaleLowerCase('vi');const list=records.filter(x=>[x.mshs,x.mst,x.company,x.procedure].some(v=>(v||'').toLocaleLowerCase('vi').includes(q)));$('recordRows').innerHTML=list.map(x=>`<tr><td>${esc(x.mshs)}</td><td>${esc(x.ngayNhan||'')}</td><td>${esc(x.mst||'')}</td><td>${esc(x.company||'')}</td><td>${esc(x.procedure||'')}</td><td><button class="edit" data-id="${x.id}">Sửa</button></td></tr>`).join('');$('emptyRecords').hidden=list.length>0;$('recordCount').textContent=records.length.toLocaleString('vi');$('companyCount').textContent=new Set(records.map(x=>x.mst).filter(Boolean)).size.toLocaleString('vi');const latest=records.map(x=>x.updatedAt).sort().at(-1);$('updatedAt').textContent=latest?new Date(latest).toLocaleDateString('vi-VN'):'—'}
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(s){$('toast').textContent=s;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2400)}
function openRecord(id){const x=records.find(r=>r.id===id)||{};$('recordId').value=x.id||'';$('mshs').value=x.mshs||'';$('ngayNhan').value=x.ngayNhan||'';$('mst').value=x.mst||'';$('company').value=x.company||'';$('procedure').value=x.procedure||'';$('note').value=x.note||'';$('recordDialog').showModal()}
async function saveRecord(){const x={id:$('recordId').value||crypto.randomUUID(),mshs:$('mshs').value.trim(),ngayNhan:$('ngayNhan').value,mst:$('mst').value.trim(),company:$('company').value.trim(),procedure:$('procedure').value.trim(),note:$('note').value.trim(),updatedAt:new Date().toISOString()};await req(tx('records','readwrite').put(x));const i=records.findIndex(r=>r.id===x.id);i<0?records.push(x):records[i]=x;render($('search').value);toast('Đã lưu hồ sơ')}
async function exportBackup(){const security=await req(tx('meta').get('security'));const payload=await encrypt({version:1,exportedAt:new Date().toISOString(),records},sessionKey);const blob=new Blob([JSON.stringify({format:'QLNHV-BACKUP',salt:security.salt,payload})],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`QLNHV-${new Date().toISOString().slice(0,10)}.qlnhv`;a.click();URL.revokeObjectURL(a.href);toast('Đã tạo file sao lưu mã hóa')}
async function importBackup(){const file=$('importFile').files[0];if(!file)return toast('Hãy chọn file sao lưu');if(!confirm('Khôi phục sẽ thay thế toàn bộ hồ sơ hiện tại. Tiếp tục?'))return;const box=JSON.parse(await file.text());if(box.format!=='QLNHV-BACKUP')throw Error('File không hợp lệ');const key=await derive($('password').value||prompt('Nhập mật khẩu của file sao lưu'),unb64(box.salt));const data=await decrypt(box.payload,key);const t=db.transaction(['records','meta'],'readwrite');t.objectStore('records').clear();data.records.forEach(x=>t.objectStore('records').put(x));const check=await keyCheck(key);t.objectStore('meta').put({key:'security',salt:box.salt,check});await new Promise((res,rej)=>{t.oncomplete=res;t.onerror=()=>rej(t.error)});sessionKey=key;records=data.records;render();toast('Khôi phục thành công')}

document.addEventListener('DOMContentLoaded',async()=>{db=await openDb();const exists=await req(tx('meta').get('security'));if(exists){$('welcomeTitle').textContent='Mở khóa';$('welcomeText').textContent='Nhập mật khẩu của thiết bị này.'}$('unlockForm').onsubmit=async e=>{e.preventDefault();try{await setupOrUnlock($('password').value)}catch{toast('Mật khẩu không đúng hoặc dữ liệu lỗi')}};$('lockBtn').onclick=lock;document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.view').forEach(v=>v.hidden=v.id!==b.dataset.view)});$('newRecord').onclick=()=>openRecord();$('search').oninput=e=>render(e.target.value);$('recordRows').onclick=e=>{const b=e.target.closest('.edit');if(b)openRecord(b.dataset.id)};$('recordForm').onsubmit=e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();saveRecord().then(()=>$('recordDialog').close()).catch(()=>toast('Mã hồ sơ đã tồn tại'))};$('exportBtn').onclick=exportBackup;$('importBtn').onclick=()=>importBackup().catch(()=>toast('Không thể đọc file hoặc sai mật khẩu'));if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js')});
