// Báo cáo thanh toán với Campuchia - nhập theo ngân hàng, tổng hợp theo quý.
const CAM_METHODS = [
  'Thanh toán thông qua ngân hàng hai nước bằng ngoại tệ tự do chuyển đổi',
  'Thanh toán bằng ngoại tệ tự do chuyển đổi hoặc VND thông qua tài khoản của thương nhân Campuchia mở tại các ngân hàng Việt Nam',
  'Thanh toán bằng VND hoặc KHR thông qua ngân hàng tỉnh biên giới'
];
const CAM_TYPES = ['Xuất khẩu','Nhập khẩu'];

function camQuarterLabel(period){const s=String(period||'');return /^\d{6}$/.test(s)?`Quý ${Number(s.slice(4))}/${s.slice(0,4)}`:s}
function camAmount(row){return Number(row&&row['SỐ TIỀN (USD)'])||0}
function camMethodIndex(value){const s=String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();if(s.includes('hai nuoc'))return 0;if(s.includes('thuong nhan campuchia'))return 1;if(s.includes('tinh bien gioi'))return 2;return CAM_METHODS.findIndex(x=>sameText(x,value))}
function camGroups(){
  const map=new Map();
  DB.Campuchia.forEach(r=>{const key=r['KỲ BC']+'||'+r['MÃ KH'];if(!map.has(key))map.set(key,{period:r['KỲ BC'],maKH:r['MÃ KH'],rows:[]});map.get(key).rows.push(r)});
  return [...map.values()];
}
function camCell(rows,method,type){const methodIndex=CAM_METHODS.indexOf(method);return rows.find(r=>camMethodIndex(r['Hình thức'])===methodIndex&&sameText(r.LoaiID,type))}

function renderCampuchia(){
  document.getElementById('topbarActions').innerHTML=`<button class="btn btn-outline" id="camAggregate">Báo cáo tổng hợp</button><button class="btn btn-primary" id="camNew">+ Nhập báo cáo</button>`;
  document.getElementById('camNew').onclick=()=>openCambodiaForm();
  document.getElementById('camAggregate').onclick=openCambodiaAggregatePrompt;
  const groups=camGroups(), customers=new Set(groups.map(g=>g.maKH)), periods=new Set(groups.map(g=>g.period));
  document.getElementById('view').innerHTML=`<div class="stats-bar"><div class="stat-chip stat-total">Báo cáo ngân hàng: <b>${groups.length}</b></div><div class="stat-chip">Ngân hàng: <b>${customers.size}</b></div><div class="stat-chip">Kỳ báo cáo: <b>${periods.size}</b></div></div>
    <div class="toolbar"><input class="search-input" id="camSearch" placeholder="Tìm kỳ, mã hoặc tên khách hàng…"><select class="select-filter" id="camPeriod"><option value="">— Tất cả kỳ —</option>${[...periods].sort().reverse().map(x=>`<option>${esc(x)}</option>`).join('')}</select></div>
    <div class="card"><div class="table-wrap"><table><thead><tr><th>Kỳ báo cáo</th><th>Mã KH</th><th>Khách hàng</th><th>Xuất khẩu (USD)</th><th>Nhập khẩu (USD)</th><th></th></tr></thead><tbody id="camBody"></tbody></table></div></div>`;
  const draw=()=>{const q=document.getElementById('camSearch').value.trim().toLowerCase(),p=document.getElementById('camPeriod').value;const list=groups.filter(g=>(!p||g.period===p)&&(!q||[g.period,g.maKH,khName(g.maKH)].join(' ').toLowerCase().includes(q))).sort((a,b)=>b.period.localeCompare(a.period)||(khName(a.maKH)||a.maKH).localeCompare(khName(b.maKH)||b.maKH,'vi'));const body=document.getElementById('camBody');body.innerHTML=list.length?list.map(g=>{const exp=g.rows.filter(r=>sameText(r.LoaiID,'Xuất khẩu')).reduce((s,r)=>s+camAmount(r),0),imp=g.rows.filter(r=>sameText(r.LoaiID,'Nhập khẩu')).reduce((s,r)=>s+camAmount(r),0);return `<tr><td class="mono"><b>${esc(g.period)}</b><br><span class="muted">${esc(camQuarterLabel(g.period))}</span></td><td class="mono">${esc(g.maKH)}</td><td><b>${esc(khName(g.maKH)||'Chưa xác định')}</b></td><td class="num">${fmtCam(exp)}</td><td class="num">${fmtCam(imp)}</td><td class="cell-actions"><button class="btn btn-outline btn-sm" data-edit="${esc(g.period+'||'+g.maKH)}">Sửa</button><button class="btn btn-danger btn-sm" data-del="${esc(g.period+'||'+g.maKH)}">Xóa</button></td></tr>`}).join(''):'<tr><td colspan="6" class="muted">Chưa có báo cáo.</td></tr>';
    body.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{const [period,maKH]=b.dataset.edit.split('||');openCambodiaForm(groups.find(g=>g.period===period&&g.maKH===maKH))});
    body.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>deleteCambodiaReport(...b.dataset.del.split('||')));
  };document.getElementById('camSearch').oninput=draw;document.getElementById('camPeriod').onchange=draw;draw();
}

function fmtCam(n){return Number(n||0).toLocaleString('vi-VN',{minimumFractionDigits:2,maximumFractionDigits:2})}
function camCustomerList(){return DB.KhachHang.slice().sort((a,b)=>(a.TenKhachHang||'').localeCompare(b.TenKhachHang||'','vi')).map(k=>`<option value="${esc(k.MaKH+' — '+k.TenKhachHang)}"></option>`).join('')}
function openCambodiaForm(group){
  const edit=!!group,period=group?group.period:'',maKH=group?group.maKH:'',rows=group?group.rows:[];
  const matrix=CAM_METHODS.map((m,i)=>`<tr><td class="num">${i+1}</td><td>${esc(m)}</td>${CAM_TYPES.map(t=>{const r=camCell(rows,m,t);return `<td><input class="cam-money" type="number" min="0" step="0.01" name="v_${i}_${t==='Xuất khẩu'?'x':'n'}" value="${r?camAmount(r):0}"></td>`}).join('')}</tr>`).join('');
  openModal(edit?'Sửa báo cáo Campuchia':'Nhập báo cáo Campuchia',`<form id="camForm"><div class="form-grid"><div class="field"><label>Kỳ báo cáo *</label><input name="period" inputmode="numeric" maxlength="6" placeholder="Ví dụ: 202601" value="${esc(period)}" ${edit?'readonly':''} required></div><div class="field"><label>Tìm và chọn khách hàng *</label><input name="customer" list="camCustomers" value="${esc(maKH?(maKH+' — '+khName(maKH)):'')}" ${edit?'readonly':''} required><datalist id="camCustomers">${camCustomerList()}</datalist><span class="hint" id="camCustomerName">${esc(khName(maKH))}</span></div></div><div class="table-wrap"><table class="cam-entry"><thead><tr><th>STT</th><th>Hình thức thanh toán</th><th>Xuất khẩu (USD)</th><th>Nhập khẩu (USD)</th></tr></thead><tbody>${matrix}</tbody></table></div><div class="field"><label>Ghi chú chung</label><textarea name="note">${esc(rows.find(r=>r['GHI CHÚ'])?.['GHI CHÚ']||'')}</textarea></div><div class="modal-foot"><button type="button" class="btn btn-outline" id="camCancel">Hủy</button><button class="btn btn-primary" id="camSave">Lưu báo cáo</button></div></form>`,el=>{el.querySelector('#camCancel').onclick=closeModal;const ci=el.querySelector('[name=customer]');ci.oninput=()=>{const id=ci.value.split(' — ')[0].trim();el.querySelector('#camCustomerName').textContent=khName(id)||'Chưa tìm thấy khách hàng'};el.querySelector('#camForm').onsubmit=async e=>{e.preventDefault();const btn=el.querySelector('#camSave');btn.disabled=true;try{const fd=new FormData(e.target),p=fd.get('period').trim(),id=fd.get('customer').split(' — ')[0].trim();if(!/^\d{6}$/.test(p)||Number(p.slice(4))<1||Number(p.slice(4))>4)throw Error('Kỳ báo cáo phải có dạng YYYY0Q, ví dụ 202601.');if(!DB.KhachHang.some(k=>k.MaKH===id))throw Error('Vui lòng chọn khách hàng trong danh sách.');for(let i=0;i<CAM_METHODS.length;i++)for(const t of CAM_TYPES){const code=t==='Xuất khẩu'?'x':'n',old=camCell(rows,CAM_METHODS[i],t),data={BCID:old?old.BCID:`${p}-${id}-${i+1}-${code}`,['KỲ BC']:p,['MÃ KH']:id,['Hình thức']:CAM_METHODS[i],LoaiID:t,['SỐ TIỀN (USD)']:Number(fd.get(`v_${i}_${code}`)||0),['GHI CHÚ']:fd.get('note')||''};await apiPost(old?'update':'create','Campuchia',data,old?old.BCID:undefined)}await reloadSheet('Campuchia');closeModal();toast('Đã lưu báo cáo '+p);renderCampuchia()}catch(err){toast(err.message,true);btn.disabled=false}}});
}
async function deleteCambodiaReport(period,maKH){if(!confirm(`Xóa báo cáo ${period} của ${khName(maKH)||maKH}?`))return;const rows=DB.Campuchia.filter(r=>r['KỲ BC']===period&&r['MÃ KH']===maKH);for(const r of rows)await apiPost('delete','Campuchia',{},r.BCID);await reloadSheet('Campuchia');toast('Đã xóa báo cáo');renderCampuchia()}

function openCambodiaAggregatePrompt(){openModal('Báo cáo tổng hợp theo quý',`<form id="camAggForm"><div class="field"><label>Kỳ báo cáo</label><input name="period" maxlength="6" inputmode="numeric" placeholder="202601" required></div><div class="modal-foot"><button type="button" class="btn btn-outline" id="camAggCancel">Hủy</button><button class="btn btn-primary">Xem báo cáo</button></div></form>`,el=>{el.querySelector('#camAggCancel').onclick=closeModal;el.querySelector('form').onsubmit=e=>{e.preventDefault();const p=new FormData(e.target).get('period').trim();if(!/^\d{4}0[1-4]$/.test(p)){toast('Kỳ phải có dạng 202601 đến 202604.',true);return}closeModal();showCambodiaAggregate(p)}})}
function buildCambodiaAggregate(period){return CAM_METHODS.map((m,i)=>({method:m,export:DB.Campuchia.filter(r=>r['KỲ BC']===period&&camMethodIndex(r['Hình thức'])===i&&sameText(r.LoaiID,'Xuất khẩu')).reduce((s,r)=>s+camAmount(r),0),import:DB.Campuchia.filter(r=>r['KỲ BC']===period&&camMethodIndex(r['Hình thức'])===i&&sameText(r.LoaiID,'Nhập khẩu')).reduce((s,r)=>s+camAmount(r),0)}))}
function showCambodiaAggregate(period){const rows=buildCambodiaAggregate(period),ex=rows.reduce((s,r)=>s+r.export,0),im=rows.reduce((s,r)=>s+r.import,0);openModal('Báo cáo thanh toán với Campuchia',`<div class="quarter-report-title"><b>BÁO CÁO TÌNH HÌNH THANH TOÁN VỚI CAMPUCHIA</b><span>${esc(camQuarterLabel(period))}</span></div><div class="report-unit">Đơn vị tính: USD</div><div class="table-wrap"><table><thead><tr><th>STT</th><th>Hình thức thanh toán</th><th>Xuất khẩu</th><th>Nhập khẩu</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td class="num">${i+1}</td><td>${esc(r.method)}</td><td class="num">${fmtCam(r.export)}</td><td class="num">${fmtCam(r.import)}</td></tr>`).join('')}<tr class="activity-grand"><td colspan="2">TỔNG CỘNG</td><td class="num">${fmtCam(ex)}</td><td class="num">${fmtCam(im)}</td></tr></tbody></table></div><div class="modal-foot"><button class="btn btn-outline" id="camCloseReport">Đóng</button><button class="btn btn-outline" id="camExcel">Xuất Excel</button><button class="btn btn-primary" id="camPdf">In / Lưu PDF</button></div>`,el=>{el.querySelector('#camCloseReport').onclick=closeModal;el.querySelector('#camExcel').onclick=()=>exportCambodiaExcel(period,rows);el.querySelector('#camPdf').onclick=()=>printCambodiaReport(period,rows)})}
function exportCambodiaExcel(period,rows){const totalX=rows.reduce((s,r)=>s+r.export,0),totalN=rows.reduce((s,r)=>s+r.import,0),lines=[['STT','Hình thức thanh toán','Xuất khẩu (USD)','Nhập khẩu (USD)'].join('\t'),...rows.map((r,i)=>[i+1,r.method,r.export,r.import].join('\t')),['','TỔNG CỘNG',totalX,totalN].join('\t')],blob=new Blob(['\ufeff'+lines.join('\r\n')],{type:'application/vnd.ms-excel;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`Bao_cao_Campuchia_${period}.xls`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function printCambodiaReport(period,rows){const totalX=rows.reduce((s,r)=>s+r.export,0),totalN=rows.reduce((s,r)=>s+r.import,0),w=window.open('','_blank');w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>BC Campuchia ${period}</title><style>@page{size:A4;margin:16mm}body{font:12px Arial;color:#111}.heads{display:grid;grid-template-columns:1fr 1fr;text-align:center;line-height:1.5}.title{text-align:center;font-size:18px;font-weight:bold;margin:22px 0 3px}.period{text-align:center;font-weight:bold}.unit{text-align:right;font-style:italic;margin:8px 0}table{width:100%;border-collapse:collapse}th,td{border:1px solid #444;padding:7px;vertical-align:top}th{background:#eee}.num{text-align:right}.total{font-weight:bold}.sign{display:grid;grid-template-columns:1fr 1fr;text-align:center;font-weight:bold;margin-top:35px}</style></head><body><div class="heads"><div><b>NGÂN HÀNG NHÀ NƯỚC VIỆT NAM<br>CHI NHÁNH KHU VỰC 2</b></div><div><b>CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM</b><br>Độc lập - Tự do - Hạnh phúc</div></div><div class="title">BÁO CÁO<br>TÌNH HÌNH THANH TOÁN VỚI CAMPUCHIA</div><div class="period">${esc(camQuarterLabel(period))}</div><div class="unit">Đơn vị tính: USD</div><table><thead><tr><th>STT</th><th>Hình thức thanh toán</th><th>Xuất khẩu</th><th>Nhập khẩu</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td>${i+1}</td><td>${esc(r.method)}</td><td class="num">${fmtCam(r.export)}</td><td class="num">${fmtCam(r.import)}</td></tr>`).join('')}<tr class="total"><td colspan="2">Tổng cộng</td><td class="num">${fmtCam(totalX)}</td><td class="num">${fmtCam(totalN)}</td></tr></tbody></table><div class="sign"><div>Nơi nhận:<br><span style="font-weight:normal">NHNN (Cục Quản lý ngoại hối)<br>Lưu: HCNS, QLNHV</span></div><div>KT. GIÁM ĐỐC<br>PHÓ GIÁM ĐỐC</div></div><script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close()}
