// Danh mục loại hình khách hàng tổ chức.
function renderLoaiHinhKhachHang(){
  document.getElementById('topbarActions').innerHTML='<button class="btn btn-primary" id="newCustomerType">+ Loại hình mới</button>';
  document.getElementById('newCustomerType').onclick=()=>openCustomerTypeForm();
  const view=document.getElementById('view');
  view.innerHTML=`<div class="stats-bar"><div class="stat-chip stat-total">Tổng số: <b>${DB.LoaiHinhKhachHang.length}</b></div></div><div class="toolbar"><input class="search-input" id="customerTypeSearch" placeholder="Tìm mã hoặc tên loại hình…"></div><div class="card"><div class="table-wrap"><table><thead><tr><th>Mã loại</th><th>Tên loại hình</th><th>Ghi chú</th><th>Số khách hàng</th><th></th></tr></thead><tbody id="customerTypeBody"></tbody></table></div></div>`;
  const draw=()=>{const q=document.getElementById('customerTypeSearch').value.trim().toLowerCase(),rows=DB.LoaiHinhKhachHang.filter(x=>!q||[x.MaLoai,x.TenLoai,x.GhiChu].join(' ').toLowerCase().includes(q)).sort((a,b)=>String(a.MaLoai).localeCompare(String(b.MaLoai),'vi'));const body=document.getElementById('customerTypeBody');body.innerHTML=rows.length?rows.map(x=>`<tr><td class="mono"><b>${esc(x.MaLoai)}</b></td><td>${esc(x.TenLoai)}</td><td class="muted">${esc(x.GhiChu)}</td><td class="num">${DB.KhachHang.filter(k=>k.LoaiToChuc===x.MaLoai).length}</td><td class="cell-actions"><button class="btn btn-outline btn-sm" data-edit="${esc(x.MaLoai)}">Sửa</button><button class="btn btn-danger btn-sm" data-del="${esc(x.MaLoai)}">Xóa</button></td></tr>`).join(''):'<tr><td colspan="5" class="muted">Chưa có loại hình khách hàng.</td></tr>';body.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openCustomerTypeForm(DB.LoaiHinhKhachHang.find(x=>x.MaLoai===b.dataset.edit)));body.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>deleteCustomerType(b.dataset.del))};document.getElementById('customerTypeSearch').oninput=draw;draw();
}
function openCustomerTypeForm(record){const edit=!!record;record=record||{};openModal(edit?'Sửa loại hình khách hàng':'Thêm loại hình khách hàng',`<form id="customerTypeForm"><div class="form-grid cols-1"><div class="field mono"><label>Mã loại *</label><input name="MaLoai" value="${esc(record.MaLoai)}" ${edit?'readonly':''} required></div><div class="field"><label>Tên loại hình *</label><input name="TenLoai" value="${esc(record.TenLoai)}" required></div><div class="field"><label>Ghi chú</label><textarea name="GhiChu">${esc(record.GhiChu)}</textarea></div></div><div class="modal-foot"><button type="button" class="btn btn-outline" id="customerTypeCancel">Hủy</button><button class="btn btn-primary">Lưu</button></div></form>`,el=>{el.querySelector('#customerTypeCancel').onclick=closeModal;el.querySelector('form').onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target).entries());data.MaLoai=data.MaLoai.trim();try{await apiPost(edit?'update':'create','LoaiHinhKhachHang',data,edit?record.MaLoai:undefined);await reloadSheet('LoaiHinhKhachHang');closeModal();toast('Đã lưu loại hình '+data.MaLoai);renderLoaiHinhKhachHang()}catch(err){toast(err.message,true)}}})}
async function deleteCustomerType(code){const used=DB.KhachHang.filter(k=>k.LoaiToChuc===code).length;if(used){toast(`Không thể xóa: đang có ${used} khách hàng sử dụng loại ${code}.`,true);return}if(!confirm(`Xóa loại hình ${code}?`))return;await apiPost('delete','LoaiHinhKhachHang',{},code);await reloadSheet('LoaiHinhKhachHang');toast('Đã xóa loại hình '+code);renderLoaiHinhKhachHang()}
