// Báo cáo tình hình giải quyết hồ sơ TTHC theo địa bàn, thủ tục và trạng thái.
function hsrParseDate(value) {
  const text=String(value||'').trim(), vn=text.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/), iso=text.match(/^(\d{4})-(\d{1,2})-(\d{1,2})/);
  if(vn)return new Date(Number(vn[3]),Number(vn[2])-1,Number(vn[1]));
  if(iso)return new Date(Number(iso[1]),Number(iso[2])-1,Number(iso[3]));
  return null;
}
function hsrISODate(date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`}
function hsrVNDate(date){return `${String(date.getDate()).padStart(2,'0')}/${String(date.getMonth()+1).padStart(2,'0')}/${date.getFullYear()}`}
function hsrProvince(row){
  const customer=DB.KhachHang.find(k=>String(k.MaKH)===String(row.MaKH)), raw=customer&&customer.DiaChiTinhTP||'Chưa xác định';
  const known=DB.TinhThanh.find(t=>provinceKey(t.TenTinh)===provinceKey(raw));
  return known?known.TenTinh:raw;
}
function hsrProcedure(row){
  const item=DB.TTHC.find(t=>String(t.MaTTHC)===String(row.MaTTHC));
  return {code:String(row.MaTTHC||'Chưa xác định'),name:item&&item.TenTTHC||tthcName(row.MaTTHC)||'Chưa xác định thủ tục'};
}
function hsrBuild(fromValue,toValue){
  const from=hsrParseDate(fromValue),to=hsrParseDate(toValue);if(!from||!to)throw Error('Ngày báo cáo không hợp lệ.');to.setHours(23,59,59,999);if(from>to)throw Error('Từ ngày không được lớn hơn đến ngày.');
  const rows=DB.HoSo.filter(r=>{const d=hsrParseDate(r.NgayTiepNhan);return d&&d>=from&&d<=to;});
  const provinces=new Map();
  rows.forEach(row=>{const province=hsrProvince(row),procedure=hsrProcedure(row),pKey=provinceKey(province),tKey=procedure.code+'|'+procedure.name;if(!provinces.has(pKey))provinces.set(pKey,{name:province,procedures:new Map(),rows:[]});const p=provinces.get(pKey);if(!p.procedures.has(tKey))p.procedures.set(tKey,{...procedure,rows:[]});p.procedures.get(tKey).rows.push(row);p.rows.push(row)});
  return {from,to,rows,provinces:[...provinces.values()].sort((a,b)=>a.name.localeCompare(b.name,'vi')).map(p=>({...p,procedures:[...p.procedures.values()].sort((a,b)=>(a.code+' '+a.name).localeCompare(b.code+' '+b.name,'vi')).map(t=>({...t,rows:t.rows.sort((a,b)=>parseVNDateSort(a.NgayTiepNhan)-parseVNDateSort(b.NgayTiepNhan)||String(a.MaHoSo).localeCompare(String(b.MaHoSo),'vi'))}))}))};
}
function hsrCounts(rows){const counts=Object.fromEntries(TRANGTHAI_HOSO.map(s=>[s,0]));rows.forEach(r=>{const status=String(r.TrangThai||'').trim();if(counts[status]!==undefined)counts[status]++});return counts}
function hsrStatusCells(row){return TRANGTHAI_HOSO.map(s=>`<td class="hsr-check">${String(row.TrangThai||'').trim()===s?'✓':''}</td>`).join('')}
function hsrCountCells(rows){const counts=hsrCounts(rows);return TRANGTHAI_HOSO.map(s=>`<td class="num"><b>${counts[s]}</b></td>`).join('')}
function hsrRoman(index){const values=['I','II','III','IV','V','VI','VII','VIII','IX','X','XI','XII','XIII','XIV','XV','XVI','XVII','XVIII','XIX','XX'];return values[index]||String(index+1)}
function hsrReportRows(data){let html='',number=0;data.provinces.forEach((province,pIndex)=>{html+=`<tr class="hsr-province"><td colspan="${TRANGTHAI_HOSO.length+2}">${hsrRoman(pIndex)}. ${esc(String(province.name).toUpperCase())} — ${province.rows.length} hồ sơ</td></tr>`;province.procedures.forEach((procedure,tIndex)=>{html+=`<tr class="hsr-procedure"><td colspan="${TRANGTHAI_HOSO.length+2}">${tIndex+1}. ${esc(procedure.code)} — ${esc(procedure.name)}</td></tr>`;procedure.rows.forEach(row=>{number++;html+=`<tr><td class="mono">${esc(row.MaHoSo)}</td><td><b>${esc(khName(row.MaKH)||'Chưa xác định')}</b><br><span class="muted mono">${esc(row.MaKH||'')}</span></td>${hsrStatusCells(row)}</tr>`});html+=`<tr class="hsr-subtotal"><td colspan="2">Tổng thủ tục: ${procedure.rows.length} hồ sơ</td>${hsrCountCells(procedure.rows)}</tr>`});html+=`<tr class="hsr-province-total"><td colspan="2">TỔNG ${esc(String(province.name).toUpperCase())}: ${province.rows.length} hồ sơ</td>${hsrCountCells(province.rows)}</tr>`});return html}
function hsrTable(data){return `<table class="hsr-table"><thead><tr><th>MÃ HỒ SƠ</th><th>TÊN DOANH NGHIỆP</th>${TRANGTHAI_HOSO.map(s=>`<th>${esc(String(s).toUpperCase())}</th>`).join('')}</tr></thead><tbody>${hsrReportRows(data)}<tr class="hsr-grand"><td colspan="2">TỔNG CỘNG: ${data.rows.length} HỒ SƠ</td>${hsrCountCells(data.rows)}</tr></tbody></table>`}
function openHoSoResolutionReportPrompt(){const now=new Date(),start=new Date(now.getFullYear(),0,1);openModal('Chọn kỳ báo cáo giải quyết TTHC',`<form id="hsrPrompt"><div class="form-grid"><div class="field"><label>Từ ngày tiếp nhận *</label><input type="date" name="from" value="${hsrISODate(start)}" required></div><div class="field"><label>Đến ngày tiếp nhận *</label><input type="date" name="to" value="${hsrISODate(now)}" required></div></div><div class="modal-foot"><button type="button" class="btn btn-outline" id="hsrCancel">Hủy</button><button class="btn btn-primary">Xem báo cáo</button></div></form>`,el=>{el.querySelector('#hsrCancel').onclick=closeModal;el.querySelector('form').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.target);try{openHoSoResolutionReport(fd.get('from'),fd.get('to'))}catch(err){toast(err.message,true)}}})}
function openHoSoResolutionReport(fromValue,toValue){const data=hsrBuild(fromValue,toValue);openModal('Báo cáo tình hình giải quyết TTHC',`<div class="quarter-report-title"><b>BÁO CÁO TÌNH HÌNH GIẢI QUYẾT THỦ TỤC HÀNH CHÍNH</b><span>Từ ngày ${hsrVNDate(data.from)} đến ngày ${hsrVNDate(data.to)} · ${data.rows.length} hồ sơ</span></div><div class="table-wrap hsr-wrap">${data.rows.length?hsrTable(data):'<div class="empty-state"><h3>Không có hồ sơ trong kỳ đã chọn</h3></div>'}</div><div class="modal-foot"><button class="btn btn-outline" id="hsrClose">Đóng</button><button class="btn btn-outline" id="hsrExcel" ${data.rows.length?'':'disabled'}>Xuất Excel</button><button class="btn btn-primary" id="hsrPrint" ${data.rows.length?'':'disabled'}>In / Lưu PDF</button></div>`,el=>{el.querySelector('#hsrClose').onclick=closeModal;if(data.rows.length){el.querySelector('#hsrExcel').onclick=()=>exportHoSoResolutionExcel(data);el.querySelector('#hsrPrint').onclick=()=>printHoSoResolutionReport(data)}})}
function exportHoSoResolutionExcel(data){const clean=v=>String(v??'').replace(/\t|\r?\n/g,' '),lines=[['Địa bàn','Mã TTHC','Tên TTHC','Mã hồ sơ','Mã KH','Tên doanh nghiệp',...TRANGTHAI_HOSO].join('\t')];data.provinces.forEach(p=>p.procedures.forEach(t=>t.rows.forEach(r=>lines.push([clean(p.name),clean(t.code),clean(t.name),clean(r.MaHoSo),clean(r.MaKH),clean(khName(r.MaKH)),...TRANGTHAI_HOSO.map(s=>String(r.TrangThai||'').trim()===s?'X':'')].join('\t')))));const blob=new Blob(['\ufeff'+lines.join('\r\n')],{type:'application/vnd.ms-excel;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`Bao-cao-giai-quyet-TTHC-${hsrISODate(data.from)}-${hsrISODate(data.to)}.xls`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function printHoSoResolutionReport(data){const w=window.open('','_blank');w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>Báo cáo giải quyết TTHC</title><style>@page{size:A4 landscape;margin:9mm}body{font:10px "Times New Roman",serif;color:#111}h1{text-align:center;font-size:16px;margin:0 0 4px}h2{text-align:center;font-size:12px;font-weight:normal;margin:0 0 10px}.hsr-table{width:100%;border-collapse:collapse}.hsr-table th,.hsr-table td{border:1px solid #666;padding:4px;vertical-align:top}.hsr-table th{text-align:center;background:#eee}.hsr-table th:nth-child(n+3),.hsr-table td:nth-child(n+3){width:8%;text-align:center}.hsr-table th:nth-child(1){width:12%}.hsr-table th:nth-child(2){width:38%}.hsr-province td{font-weight:bold;font-size:12px;background:#dcebe5}.hsr-procedure td{font-weight:bold;background:#edf5f2}.hsr-subtotal td,.hsr-province-total td,.hsr-grand td{font-weight:bold}.hsr-province-total td{background:#f1f1f1}.hsr-grand td{background:#ddd}.mono{font-family:monospace}.muted{font-size:9px;color:#555}.num,.hsr-check{text-align:center}</style></head><body><h1>BÁO CÁO TÌNH HÌNH GIẢI QUYẾT THỦ TỤC HÀNH CHÍNH</h1><h2>Từ ngày ${hsrVNDate(data.from)} đến ngày ${hsrVNDate(data.to)}</h2>${hsrTable(data)}<script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close()}
